### ISSUE TITLE
Steering via web-application

### ISSUE THREAD

**Issue by OscarBogren** [DIT112-V19/group-03#1]
## Use case
As a driver, I want to be able to control the direction of the car on any of my devices with access to the web so that I can steer it correctly.

## Acceptance criteria 
The cars actions should correspond correctly to the drivers inputs.
The drivers inputs includes going forward, backwards, right, left, stop and speed control (faster and slower).

Forward → Increases to the default speed of 0.2 m/s.

Faster → Accelerates the car: Speed + 0.2 m/s up to a maximum of 1 m/s.

Slower → Decelerates the car: Speed - 0.2 m/s.

Stop → Sets the speed to 0 m/s.

Right → Rotates the car 90 degrees clockwise.

Left →  Rotates the car 90 degrees anti-clockwise.

**Comment by platisd** [comment]
Which user of the system are you referring to?

**Comment by OscarBogren** [comment]
Oops! Edited now, thanks for the heads up!
