### ISSUE TITLE
Expand camera view

### ISSUE THREAD

**Issue by LinneaStigholt** [DIT112-V19/group-03#14]
## Use case:
As a driver, I want to be able to expand the camera view into fullscreen so that I can get a closer look at my surroundings. 

## Acceptance criteria:
The camera feed should cover the entire screen.
The screen size should be adjustable from full to the standard screen view.
The standard screen view should take up 60% of the screen.

**Comment by platisd** [comment]
@nafenk @LinneaStigholt you can assign the issue to both of you to indicate that you worked together on this one.
